name: Build Artifact on PR
on:
  pull_request:
    types: 
      - opened
      - synchronize
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      
      - name: Setup Yarn 🧶
        run: |
          corepack enable
          yarn set version stable

      - name: Install and Build 🔧
        run: |
          yarn install
          yarn build
      
      - name: Upload artifacts 📦
        uses: actions/upload-artifact@v4
        with:
          name: gh-pages
          path: dist
          retention-days: 5